# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-04 04:50
from __future__ import unicode_literals

import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=30, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=30, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('user_phone', models.CharField(blank=True, max_length=11, verbose_name='电话')),
                ('user_eid', models.CharField(blank=True, max_length=19, verbose_name='身份证号')),
                ('user_school', models.CharField(blank=True, max_length=20, verbose_name='学校名字')),
                ('user_start_year', models.CharField(blank=True, max_length=4, verbose_name='入学年份')),
                ('user_xueli', models.CharField(blank=True, max_length=2, verbose_name='学历')),
                ('user_year', models.IntegerField(blank=True, default=4, verbose_name='几年制')),
                ('user_xuehao', models.CharField(blank=True, max_length=20, verbose_name='学号')),
                ('user_xszimg', models.ImageField(blank=True, upload_to='xszimg', verbose_name='学生证正面')),
                ('user_qq', models.CharField(blank=True, max_length=10, verbose_name='QQ')),
                ('user_wechat', models.CharField(blank=True, max_length=15, verbose_name='微信')),
                ('user_shanchang', models.CharField(blank=True, max_length=50, verbose_name='擅长')),
                ('user_xuanyan', models.CharField(blank=True, max_length=50, verbose_name='宣言')),
                ('user_isValid', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
