# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-28 14:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logre', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='user_eid',
            field=models.CharField(blank=True, max_length=19, verbose_name='身份证号'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='user_isValid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='user_qq',
            field=models.CharField(blank=True, max_length=10, verbose_name='QQ'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='user_school',
            field=models.CharField(blank=True, max_length=20, verbose_name='学校名字'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='user_shanchang',
            field=models.CharField(blank=True, max_length=50, verbose_name='擅长'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='user_start_year',
            field=models.CharField(blank=True, max_length=4, verbose_name='入学年份'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='user_wechat',
            field=models.CharField(blank=True, max_length=15, verbose_name='微信'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='user_xszimg1',
            field=models.ImageField(blank=True, upload_to='xszimg1'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='user_xszimg2',
            field=models.ImageField(blank=True, upload_to='xszimg2'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='user_xuanyan',
            field=models.CharField(blank=True, max_length=50, verbose_name='宣言'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='user_xuehao',
            field=models.CharField(blank=True, max_length=20, verbose_name='学号'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='user_xueli',
            field=models.CharField(blank=True, max_length=2, verbose_name='学历'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='user_year',
            field=models.IntegerField(blank=True, default=4, verbose_name='几年制'),
        ),
    ]
