# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-05-13 06:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logre', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=30, verbose_name='浏览的标题')),
                ('see_people', models.CharField(blank=True, max_length=10, verbose_name='浏览者')),
                ('time', models.DateTimeField(verbose_name='浏览时间')),
            ],
            options={
                'verbose_name_plural': '用户浏览表',
                'verbose_name': '用户浏览表',
                'db_table': 'see_user',
            },
        ),
        migrations.AlterField(
            model_name='user',
            name='user_xueli',
            field=models.CharField(blank=True, max_length=10, verbose_name='学历'),
        ),
    ]
