# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-05-13 07:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logre', '0002_auto_20170513_1451'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersee',
            name='cate',
            field=models.CharField(blank=True, max_length=10, verbose_name='类别'),
        ),
        migrations.AddField(
            model_name='usersee',
            name='pub_author',
            field=models.CharField(blank=True, max_length=10, verbose_name='发布者'),
        ),
    ]
