# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-28 14:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logre', '0002_auto_20170228_2232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='user_xszimg1',
            field=models.ImageField(blank=True, upload_to='xszimg1', verbose_name='学生证正面'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user_xszimg2',
            field=models.ImageField(blank=True, upload_to='xszimg2', verbose_name='学生证反面'),
        ),
    ]
