# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-05-13 07:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logre', '0003_auto_20170513_1536'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersee',
            name='image',
            field=models.CharField(blank=True, max_length=100, verbose_name='图像信息'),
        ),
    ]
