# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-04 07:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cate_name', models.CharField(max_length=30, verbose_name='类别标题')),
                ('cate_time', models.DateTimeField(verbose_name='添加时间')),
                ('cate_num', models.IntegerField(unique=True, verbose_name='类别编号')),
            ],
            options={
                'db_table': 'cate_table',
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('new_title', models.CharField(max_length=30, verbose_name='标题')),
                ('new_author', models.CharField(max_length=15, verbose_name='发布人')),
                ('new_time', models.DateTimeField(verbose_name='发布时间')),
                ('new_seenum', models.IntegerField(default=0, verbose_name='浏览次数')),
                ('new_content', models.TextField(verbose_name='内容')),
                ('new_cate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.cate', verbose_name='类别')),
            ],
            options={
                'db_table': 'news_table',
            },
        ),
    ]
