# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-09 16:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('new_id', models.IntegerField(verbose_name='文章id')),
                ('father_id', models.IntegerField(blank=True, verbose_name='父id')),
                ('m_content', models.TextField(verbose_name='评论内容')),
                ('m_time', models.DateTimeField(verbose_name='评论时间')),
                ('m_people', models.CharField(max_length=15, verbose_name='留言人')),
            ],
            options={
                'verbose_name': '留言',
                'db_table': 'message',
                'verbose_name_plural': '留言信息',
            },
        ),
        migrations.AlterModelOptions(
            name='cate',
            options={'verbose_name': '类别', 'verbose_name_plural': '类别管理'},
        ),
        migrations.AlterModelOptions(
            name='news',
            options={'verbose_name': 'CSM动态', 'verbose_name_plural': '素材管理'},
        ),
    ]
