# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-23 14:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_auto_20170310_0003'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='new_main',
            field=models.CharField(blank=True, max_length=50, verbose_name='摘要'),
        ),
    ]
