# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-23 14:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_news_new_main'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='new_main',
            field=models.TextField(blank=True, max_length=100, verbose_name='摘要'),
        ),
    ]
