# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-24 15:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_auto_20170323_2250'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='message',
            new_name='Words',
        ),
        migrations.AlterModelOptions(
            name='cate',
            options={'verbose_name': '动态类别', 'verbose_name_plural': '动态类别管理'},
        ),
        migrations.AlterModelTable(
            name='cate',
            table='cate_news_table',
        ),
        migrations.AlterModelTable(
            name='words',
            table='words_table',
        ),
    ]
