# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-24 16:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mess_title', models.CharField(max_length=30, verbose_name='标题')),
                ('mess_image', models.ImageField(height_field=100, upload_to='', verbose_name='图像信息', width_field=100)),
                ('mess_author', models.CharField(max_length=15, verbose_name='发布人')),
                ('mess_time', models.DateTimeField(verbose_name='发布时间')),
                ('mess_price', models.FloatField(default=0.0, verbose_name='交易报价')),
                ('mess_seenum', models.IntegerField(default=0, verbose_name='浏览次数')),
                ('mess_hezuo', models.CharField(blank=True, max_length=15, verbose_name='合作方')),
                ('mess_ifsuccess', models.BooleanField(default=False, verbose_name='交易是否成功')),
                ('mess_content', models.TextField(verbose_name='具体描述')),
                ('mess_cate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='message.Cate', verbose_name='类别')),
            ],
            options={
                'verbose_name_plural': '交易信息',
                'verbose_name': '交易信息',
                'db_table': 'message_table',
            },
        ),
    ]
