# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-26 04:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0002_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mwords',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mess_id', models.IntegerField(verbose_name='服务需求id')),
                ('father_id', models.IntegerField(blank=True, verbose_name='父id')),
                ('mw_content', models.TextField(verbose_name='评论内容')),
                ('mw_time', models.DateTimeField(verbose_name='评论时间')),
                ('mw_people', models.CharField(max_length=15, verbose_name='留言人')),
            ],
            options={
                'db_table': 'message_words_table',
                'verbose_name_plural': '服务需求留言',
                'verbose_name': '服务需求留言',
            },
        ),
    ]
