# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-04 08:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0003_mwords'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'verbose_name': '素材管理', 'verbose_name_plural': '素材管理'},
        ),
        migrations.AddField(
            model_name='message',
            name='mess_xuorfu',
            field=models.CharField(default=None, max_length=2, verbose_name='需求or服务'),
        ),
    ]
