# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-06 17:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0004_auto_20170404_1646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='mess_image',
            field=models.CharField(blank=True, max_length=100, verbose_name='图像信息'),
        ),
    ]
