# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-05-06 17:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0006_auto_20170426_0113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dmessage',
            name='dmess_cate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='message.DCate', verbose_name='类别'),
        ),
    ]
