# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-05-26 15:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0007_auto_20170507_0122'),
    ]

    operations = [
        migrations.AddField(
            model_name='dmessage',
            name='dmess_compeletenum',
            field=models.IntegerField(default=0, verbose_name='已成交次数'),
        ),
        migrations.AddField(
            model_name='dmessage',
            name='dmess_totalnum',
            field=models.IntegerField(default=1, verbose_name='有效总次数'),
        ),
        migrations.AddField(
            model_name='message',
            name='mess_compeletenum',
            field=models.IntegerField(default=0, verbose_name='已成交次数'),
        ),
        migrations.AddField(
            model_name='message',
            name='mess_totalnum',
            field=models.IntegerField(default=1, verbose_name='有效总次数'),
        ),
        migrations.AlterField(
            model_name='dmessage',
            name='dmess_image',
            field=models.ImageField(blank=True, upload_to='fengmian', verbose_name='图像信息'),
        ),
        migrations.AlterField(
            model_name='message',
            name='mess_image',
            field=models.ImageField(blank=True, upload_to='fengmian', verbose_name='图像信息'),
        ),
    ]
