# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-05-06 17:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='doc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='标题')),
                ('see_num', models.IntegerField(default=0, verbose_name='浏览次数')),
                ('pub_date', models.DateTimeField(verbose_name='发布时间')),
                ('show', models.TextField(verbose_name='内容')),
            ],
            options={
                'db_table': 'doc_table',
                'verbose_name': '技术文档',
                'verbose_name_plural': '技术文档',
            },
        ),
        migrations.CreateModel(
            name='example',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='标题')),
                ('image', models.ImageField(upload_to='')),
                ('pub_date', models.DateTimeField(verbose_name='发布时间')),
                ('see_num', models.IntegerField(default=0, verbose_name='浏览次数')),
                ('service_obj', models.CharField(max_length=30, verbose_name='服务对象')),
                ('chengjiao_time', models.DateTimeField(verbose_name='成交时间')),
                ('show', models.TextField(verbose_name='内容')),
            ],
            options={
                'db_table': 'example_table',
                'verbose_name': '案例',
                'verbose_name_plural': '案例素材',
            },
        ),
    ]
