# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-05-07 10:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cyanscikit', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='example',
            name='jianjie',
            field=models.TextField(default='', verbose_name='简介'),
        ),
        migrations.AlterField(
            model_name='example',
            name='image',
            field=models.ImageField(blank=True, upload_to='example', verbose_name='案例封面'),
        ),
    ]
